remote_theme: mmistakes/minimal-mistakes
title: Mom On Linux
description: Documenting my path to mastering software engineering skills

minimal_mistakes_skin: "sunrise"
plugins:
  - jekyll-include-cache

locale: "en-US"
# Tell the theme to show the Sidebar Profile
# author:
#   name: "Mom on Linux"
#   bio: "Documenting my path to mastering technical skills"
  # avatar: "/assets/images/profile.jpg"
