remote_theme: mmistakes/minimal-mistakes
title: Mom on Linux
description: Documenting my path to mastering technical skills

minimal_mistakes_skin: "sunrise"
plugins:
  - jekyll-include-cache

locale: "en-US"
# Tell the theme to show the Sidebar Profile
author:
  name: "Mom on Linux"
  bio: "Software Engineer & Learner"
  # avatar: "/assets/images/profile.jpg"
